#!/bin/bash
set -o errexit
set -o nounset


celery -A services.asyncq worker -l INFO --concurrency=5 -n worker_default@%h \
& celery -A services.asyncq worker -l INFO --concurrency=1 -Q fifo -n worker_fifo@%h