#!/bin/bash
set -o errexit
set -o nounset

python manage.py migrate django_celery_beat

rm -f './celerybeat.pid'
celery -A services.asyncq beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler