version: '3.8'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  web: &web
    build:
      context: .
      dockerfile: ./compose/local/services/Dockerfile
    depends_on:
      - postgres
      - redis
      - rmq
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.services
      - ./.envs/.local/.postgres
      - ./.envs/.local/.s3
      - ./.envs/.local/.rmq
    environment:
      PORT: 9001
    ports:
      - "9001:9001"
    restart: unless-stopped
    command: /start
    networks:
      - default
      - localstack_service_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6.0-alpine

  celeryworker:
     <<: *web
     image: celeryworker_local
     depends_on:
       - redis
       - postgres
       - web
       - celerybeat
     command: /start-worker
     ports: [ ]

  celerybeat:
     <<: *web
     image: celerybeat_local
     depends_on:
       - web
       - postgres
       - redis
     command: /start-beat
     ports: [ ]

  rmq:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
    env_file:
      - ./.envs/.local/.rmq

networks:
  localstack_service_network:
    external: true