# Generated by Django 4.0.3 on 2022-09-07 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django_celery_beat.models import IntervalSchedule, PeriodicTask

TOKEN_DELETING_TASK = {"name": "Token deleting task", "task": "services.asyncq.core_tasks.token_expiration.delete_expired_tokens"}


###############################################################################
def add_deleting_task(apps, schema_editor):
    schedule = IntervalSchedule.objects.create(every=30, period=IntervalSchedule.SECONDS)
    PeriodicTask.objects.create(interval=schedule, **TOKEN_DELETING_TASK)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('valid_until', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.RunPython(add_deleting_task),

    ]
