# Generated by Django 4.2 on 2023-08-27 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import services.core.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.directory', blank=True, null=True),
        ),
    ]
